return {
  -- Syntax plugins
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      highlight = {
        enable = not vim.g.vscode,
      },
    },
  },
  { "nvim-treesitter/playground", enabled = not vim.g.vscode },
  { "LuaSnip", enabled = not vim.g.vscode },
  { "alpha-nvim", enabled = not vim.g.vscode },
  { "bufferline.nvim", enabled = not vim.g.vscode },
  { "catppuccin", enabled = not vim.g.vscode },
  { "cmp-buffer", enabled = not vim.g.vscode },
  { "cmp-nvim-lsp", enabled = not vim.g.vscode },
  { "cmp-path", enabled = not vim.g.vscode },
  { "cmp_luasnip", enabled = not vim.g.vscode },
  { "dressing.nvim", enabled = not vim.g.vscode },
  { "friendly-snippets", enabled = not vim.g.vscode },
  { "gitsigns.nvim", enabled = not vim.g.vscode },
  { "lukas-reineke/indent-blankline.nvim", enabled = not vim.g.vscode },
  { "lazy.nvim", enabled = not vim.g.vscode },
  { "lualine.nvim", enabled = not vim.g.vscode },
  { "mason-lspconfig.nvim", enabled = not vim.g.vscode },
  { "mason.nvim", enabled = not vim.g.vscode },
  { "neo-tree.nvim", enabled = not vim.g.vscode },
  { "nvim-cmp", enabled = not vim.g.vscode },
  { "nvim-lspconfig", enabled = not vim.g.vscode },
  { "nvim-navic", enabled = not vim.g.vscode },
  { "nvim-notify", enabled = not vim.g.vscode },
  { "nvim-spectre", enabled = not vim.g.vscode },
  { "nvim-web-devicons", enabled = not vim.g.vscode },
  { "obsidian", enabled = not vim.g.vscode },
  { "playground", enabled = not vim.g.vscode },
  { "plenary.nvim", enabled = not vim.g.vscode },
  { "telescope.nvim", enabled = not vim.g.vscode },
  { "trouble.nvim", enabled = not vim.g.vscode },
  { "vim-illuminate", enabled = not vim.g.vscode },
  { "which-key.nvim", enabled = not vim.g.vscode },
  { "noice.nvim", enabled = not vim.g.vscode },
  { "nui.nvim", enabled = not vim.g.vscode },
  { "dashboard-nvim", enabled = not vim.g.vscode },
  { "conform.nvim", enabled = not vim.g.vscode },
  { "nvim-lint", enabled = not vim.g.vscode },
  { "mini.pairs", enabled = not vim.g.vscode },
  { "persistence.nvim", enabled = not vim.g.vscode },
}
